language: node_js
node_js: node
services: mongodb
env:
  matrix:
    secure: RWtuh52EPkbbOJa7YsBbgwpAjNvKtBESJKiV3XiHcdJ17ZX83e4QHAoZEL2YusrmSwE+VGlE0whXiH9lsm/eACnRMZEfjBBoso5KSWP9oHevtRZmZKIDfgQxQuVTLXwzAjumXT6Cs5UdvPt7MKFcLCuo19YVlhDyNpjwfIIz+RukGi7pTOe/i6D6OK2fgc7DPAqZx+ZQ6K7lf9qSf54IQ+gASEl1H0MITTHBFZYgMOUC0Skm2BpLtZ7EMrt5/oM5fZdoEQ7eOjWzdZ/OPAqZnEcETduQCO8mb9rDjGNoG1C8A/kEtYJ2CalRRwX3ehWE2YNFV43AN9h5XTMEKB4gxy9z8m4zlaaQTraSVqyiwMfj9n2O3XVAU6E7yLRfAb4tRsRDh9FTPlC/x2TrqEwPCWdZIbmwaJ9uvy8Gsz4zxYtoC0Et6i9Jdp2z+4tnqvxczRCeMClnFZAJj64ctZM3O4ss/DoGHQ1UXEj0MSW2NX0znBzyseHlCnykgAY/Xy1S1ID1me8EvAZwnXYdKhWKlLInM4iSgjWFqkOHF5qUhz2l1FKNhOPz01jF8+6ZZpTrkFMJTDcD4QUWdjCbbIRePpvqzi5seIKq+op1k7YEGfcsndVKfPxwA0Ga1XgMtJ5F+6lMWFMrm5upCtr1R76gUg0ew3gjTMZuT+tHr+i6jpU=
